### ISSUE TITLE
Improve Virtualization samples

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular-samples#1958]
- [x] Increase the size of remote chunks to around 50 records for the first sample so it only loads new data once per full scroll top to bottom - #2037 
- [x] In the sample showing value masks for cells, only show them for rows that are being newly added - #2047 
- [x] Add a sample that works as though you are appending rows on demand by getting the totalRowCount from the caching service instead of from the server (so it updates every time a new chunk is loaded) - #1975
